-- Legacy migration notice
--
-- This file used to be a one-shot migration for an older development schema.
-- It no longer represents the current application schema and should not be run.
--
-- For a fresh install, use:
--   mysql -u root -p < db/schema.sql
--   npm run seed
--
-- For an existing install, use the numbered migrations in db/migrations/ in order,
-- or write a targeted migration from the live schema state you are upgrading.
--
-- This file intentionally contains no schema-changing statements.
